apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ace-app           # <--- Must act as a placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ace-app
  template:
    metadata:
      labels:
        app: my-ace-app
    spec:
      containers:
      - name: ace-container
        image: test-runtime:v1   # <--- Must be this exact placeholder string
        imagePullPolicy: Never
        ports:
        - containerPort: 7800
        env:
        - name: LICENSE
          value: "accept"
        - name: ACE_SERVER_NAME
          value: "MyK8sRuntime"

---
apiVersion: v1
kind: Service
metadata:
  name: my-ace-service       # <--- Placeholder
spec:
  type: LoadBalancer
  selector:
    app: my-ace-app
  ports:
    - protocol: TCP
      port: 8080             # <--- Must be 8080 (so our script can find it)
      targetPort: 7800